"""add created_at to todos

Revision ID: 451da1be718a
Revises: c73b68f606d5
Create Date: 2026-09-01 10:11:43.622192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451da1be718a'
down_revision: Union[str, Sequence[str], None] = 'c73b68f606d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'todos',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
